# Generated by Django 2.0 on 2018-01-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifworld', '0004_auto_20180124_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csgogif',
            name='image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='owgif',
            name='image',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
